Repository astroconda/astroconda-contrib, pull requests merged in 2018-03, with the labels that each got.

#328 Drizzlepac release 2.1.22: Improved create median step. Updated documentation
  drizzlepac/meta.yaml
Labels: upgrade

#329 Cfitsio: curl
  cfitsio/build.sh
  cfitsio/meta.yaml
Labels: enhancement

#330 Initial commits of ccdproc, reproject, astropy-healpix, astroscrappy
  astropy-healpix/bld.bat
  astropy-healpix/build.sh
  astropy-healpix/meta.yaml
  astroscrappy/bld.bat
  astroscrappy/build.sh
  astroscrappy/meta.yaml
  ccdproc/bld.bat
  ccdproc/build.sh
  ccdproc/meta.yaml
  reproject/bld.bat
  reproject/build.sh
  reproject/meta.yaml
Labels: new

#331 Update ccdproc to 1.3.0.post1
  ccdproc/meta.yaml
Labels: upgrade

#332 ccdproc: add missing requirement
  ccdproc/meta.yaml
Labels: bug

#333 Add stsci_rtd_theme
  stsci_rtd_theme/bld.bat
  stsci_rtd_theme/build.sh
  stsci_rtd_theme/meta.yaml
Labels: new
