Repository astroconda/astroconda-contrib, pull requests merged in 2018-08, with the labels that each got.

#387 Update photutils to v0.5
  photutils/meta.yaml
Labels: upgrade

#385 cfitsio: disable cURL
  cfitsio/0001-cfitsio-autoconf-disable-curl.patch
  cfitsio/build.sh
  cfitsio/meta.yaml
  crds/meta.yaml
  fitsverify/meta.yaml
  hstcal/build.sh
  hstcal/meta.yaml
  stsci/meta.yaml
Labels: bug

#392 Initial commit of semantic_version
  semantic_version/bld.bat
  semantic_version/build.sh
  semantic_version/meta.yaml
Labels: new

#390 update stsci.tools to 3.4.13
  stsci.tools/meta.yaml
Labels: data processing, upgrade

#395 stsci.imagemanip: Update 1.1.2 -> 1.1.4
  stsci.imagemanip/meta.yaml
Labels: upgrade

#396 Deprecate pyregion
  pyregion/meta.yaml
  stsci-hst/meta.yaml
Labels: deprecation
