Repository astroconda/astroconda-contrib, pull requests merged in 2018-11, with the labels that each got.

#388 Bump acstools to 2.1.0
  acstools/meta.yaml
Labels: data processing, upgrade

#389 update stwcs version to 1.4.2
  stwcs/meta.yaml
Labels: data processing, upgrade

#424 Fix py37 package resolution failures
  conda_build_config.yaml
  stsci-data-analysis/meta.yaml
  stsci-hst/meta.yaml
  stsci/meta.yaml
Labels: bug, upgrade

#425 sphinxcontrib-programoutput: Update to 0.11 (#172)
  sphinxcontrib-programoutput/meta.yaml
Labels: from dev, upgrade

#427 crds: Disable python 2.7 (no longer works)
  crds/meta.yaml
Labels: bug, enhancement

#428 stsci.imagestats: Disable python 2.7
  stsci.imagestats/meta.yaml
Labels: enhancement

#429 Aggressive compatibility sweep
  astropy-healpix/meta.yaml
  astroscrappy/build.sh
  astroscrappy/meta.yaml
  ccdproc/meta.yaml
  reproject/build.sh
  reproject/meta.yaml
Labels: bug
