Repository astroconda/astroconda-contrib, pull requests merged in 2018-02, with the labels that each got.

#307 stsci.tools: 3.4.11 -> 3.4.12
  stsci.tools/meta.yaml
Labels: upgrade

#308 stsci.tools: Add missing pytest-runner requirement
  stsci.tools/meta.yaml
Labels: bug

#309 Fixup d2to1 recipes
  costools/meta.yaml
  drizzlepac/meta.yaml
  nictools/meta.yaml
Labels: bug

#310 Initial commit of radio-beam
  radio-beam/bld.bat
  radio-beam/build.sh
  radio-beam/meta.yaml
Labels: new

#311 Initial commit of spectral-cube
  spectral-cube/bld.bat
  spectral-cube/build.sh
  spectral-cube/meta.yaml
Labels: new

#312 specviz: add missing dependency
  specviz/meta.yaml
Labels: bug

#302 Bump acstools to 2.0.10
  acstools/meta.yaml
Labels: upgrade

#315 calcos 3.3.4
  calcos/meta.yaml
Labels: upgrade

#314 hstcal 2.0.0
  hstcal/meta.yaml
Labels: upgrade

#316 Bump Ginga to 2.7 and stginga to 0.3
  ginga/meta.yaml
  stginga/meta.yaml
Labels: upgrade
