Repository astroconda/astroconda-contrib, pull requests merged in 2019-05, with the labels that each got.

#508 Bug fix in 2D-histogram intitial shift estimation
  tweakwcs/meta.yaml
Labels: upgrade

#512 Remove outdated/deprecated stsci.sphinxext from HST metapackage
  stsci-hst/meta.yaml
Labels: deprecation

#513 costools: update 1.2.3
  costools/meta.yaml
Labels: bug

#514 nictools: update 1.1.4
  nictools/meta.yaml
Labels: bug
