Repository astroconda/astroconda-contrib, pull requests merged in 2019-07, with the labels that each got.

#519 Update stsci.tools and stwcs versions
  stsci.tools/meta.yaml
  stwcs/meta.yaml
Labels: cumulative

#525 stsci.tools -> 3.6.0
  stsci.tools/meta.yaml
Labels: upgrade

#526 calcos -> 3.3.7
  calcos/bld.bat
  calcos/build.sh
  calcos/meta.yaml
Labels: upgrade

#528 calcos -> 3.3.7
  calcos/bld.bat
  calcos/build.sh
  calcos/meta.yaml
Labels: upgrade

#529 hstcal -> 2.3.0rc1
  hstcal/meta.yaml
Labels: upgrade

#530 mosviz: add setuptools_scm
  mosviz/meta.yaml
Labels: bug

#531 cubeviz: use correct tag
  cubeviz/meta.yaml
Labels: bug

#532 cubeviz: add setuptools_scm
  cubeviz/meta.yaml
Labels: bug

#523 pyopengl -> 3.1.3b1
  pyopengl/meta.yaml
Labels: upgrade

#522 pyopengl-accelerate -> 3.1.3b1
  pyopengl-accelerate/meta.yaml
Labels: upgrade

#533 spectral-cube -> 0.4.4
  spectral-cube/meta.yaml
Labels: bug

#534 cubeviz: expects spectral-cube "<" not ">=" 0.4.4
  cubeviz/meta.yaml
Labels: bug

#535 cubeviz: Use pyqt from defaults
  cubeviz/build.sh
  cubeviz/meta.yaml
Labels: bug
